from sqlalchemy import Boolean, Column, Float, Integer, String, Date, Text, ForeignKey
from sqlalchemy.orm import relationship
from app.core.tenant_database import Base
from app.modules.gen.models.ciudad import Ciudad


class Contrato(Base):
    __tablename__ = "rhu_contrato"

    codigo_contrato_pk              = Column(Integer, primary_key=True, index=True)
    codigo_empleado_fk              = Column(Integer, ForeignKey("rhu_empleado.codigo_empleado_pk"), nullable=True)
    codigo_contrato_tipo_fk         = Column(String(10), ForeignKey("rhu_contrato_tipo.codigo_contrato_tipo_pk"), nullable=True)
    codigo_contrato_clase_fk        = Column(String(10), nullable=True)
    codigo_clasificacion_riesgo_fk  = Column(String(10), nullable=True)
    codigo_contrato_motivo_fk       = Column(String(10), nullable=True)
    codigo_tiempo_fk                = Column(String(10), nullable=True)
    codigo_salario_tipo_fk          = Column(String(10), nullable=True)
    codigo_pension_fk               = Column(String(10), nullable=True)
    codigo_salud_fk                 = Column(String(10), nullable=True)
    codigo_cargo_fk                 = Column(String(10), ForeignKey("rhu_cargo.codigo_cargo_pk"), nullable=True)
    codigo_grupo_fk                 = Column(String(10), ForeignKey("rhu_grupo.codigo_grupo_pk"), nullable=True)
    codigo_tipo_cotizante_fk        = Column(String(10), nullable=True)
    codigo_subtipo_cotizante_fk     = Column(String(10), nullable=True)
    codigo_entidad_salud_fk         = Column(Integer, ForeignKey("rhu_entidad.codigo_entidad_pk"), nullable=True)
    codigo_entidad_pension_fk       = Column(Integer, ForeignKey("rhu_entidad.codigo_entidad_pk"), nullable=True)
    codigo_entidad_cesantia_fk      = Column(Integer, ForeignKey("rhu_entidad.codigo_entidad_pk"), nullable=True)
    codigo_entidad_caja_fk          = Column(Integer, ForeignKey("rhu_entidad.codigo_entidad_pk"), nullable=True)
    codigo_ciudad_contrato_fk       = Column(Integer, ForeignKey("gen_ciudad.codigo_ciudad_pk"), nullable=True)
    codigo_ciudad_labora_fk         = Column(Integer, ForeignKey("gen_ciudad.codigo_ciudad_pk"), nullable=True)
    codigo_costo_clase_fk           = Column(String(10), nullable=True)
    codigo_costo_tipo_fk            = Column(String(10), nullable=True)
    codigo_centro_trabajo_fk        = Column(String(10), nullable=True)
    codigo_centro_operacion_fk      = Column(String(10), nullable=True)
    codigo_sucursal_fk              = Column(String(10), nullable=True)
    codigo_centro_costo_fk          = Column(String(20), nullable=True)
    codigo_nivel_fk                 = Column(String(50), nullable=True)
    codigo_distribucion_fk          = Column(String(10), nullable=True)
    codigo_tercero_fk               = Column(Integer, ForeignKey("gen_tercero.codigo_tercero_pk"), nullable=True)
    codigo_puesto_fk                = Column(Integer, ForeignKey("tur_puesto.codigo_puesto_pk"), nullable=True)
    codigo_examen_fk                = Column(Integer, nullable=True)
    codigo_dotacion_fk              = Column(Integer, nullable=True)
    codigo_empresa_fk               = Column(Integer, nullable=True)
    codigo_jefe_fk                  = Column(Integer, nullable=True)

    fecha                           = Column(Date, nullable=True)
    fecha_desde                     = Column(Date, nullable=True)
    fecha_hasta                     = Column(Date, nullable=True)
    fecha_ultimo_pago_cesantias     = Column(Date, nullable=True)
    fecha_ultimo_pago_vacaciones    = Column(Date, nullable=True)
    fecha_ultimo_pago_primas        = Column(Date, nullable=True)
    fecha_ultimo_pago               = Column(Date, nullable=True)
    fecha_ultimo_pago_aporte        = Column(Date, nullable=True)
    fecha_bloqueo_aporte            = Column(Date, nullable=True)
    fecha_dotacion                  = Column(Date, nullable=True)

    numero                          = Column(String(30), nullable=True)
    cargo_descripcion               = Column(Text, nullable=True)
    comentario                      = Column(String(2000), nullable=True)
    comentario_terminacion          = Column(String(2000), nullable=True)
    dia_semana_descanso             = Column(String(1), default="7")

    vr_salario                      = Column(Float, default=0.0, nullable=True)
    vr_salario_pago                 = Column(Float, default=0.0, nullable=True)
    vr_adicional                    = Column(Float, default=0.0, nullable=True)
    vr_adicional_prestacional       = Column(Float, default=0.0, nullable=True)
    vr_devengado_pactado            = Column(Float, default=0.0, nullable=True)
    ibp_cesantias_inicial           = Column(Float, default=0.0, nullable=True)
    ibp_primas_inicial              = Column(Float, default=0.0, nullable=True)
    ibp_recargo_nocturno_inicial    = Column(Float, default=0.0, nullable=True)
    anticipo_cesantias_ley_anterior = Column(Float, default=0.0, nullable=True)

    factor_horas_dia                = Column(Integer, default=0, nullable=True)
    numero_prorrogas                = Column(Integer, nullable=True)

    estado_terminado                = Column(Boolean, default=False)
    indefinido                      = Column(Boolean, default=False)
    reingreso                       = Column(Boolean, default=False)
    salario_integral                = Column(Boolean, default=False)
    auxilio_transporte              = Column(Boolean, default=False)
    habilitado_turno                = Column(Boolean, default=False)
    turno_fijo                      = Column(Boolean, default=False)
    estado_migrado                  = Column(Boolean, default=False)
    pagado_entidad                  = Column(Boolean, default=False, nullable=True)
    suspension_permanente           = Column(Boolean, default=False, nullable=True)
    sindicato                       = Column(Boolean, default=False)
    integrado_pay_flow              = Column(Boolean, default=False)
    cerrado_nomina                  = Column(Boolean, default=False)
    dia31_completo                  = Column(Boolean, default=False)
    prestaciones_dias_calendario    = Column(Boolean, default=False)
    multiples_puestos               = Column(Boolean, default=False)
    ley_anterior_cesantias          = Column(Boolean, default=False)

    empleado_rel        = relationship("Empleado",      foreign_keys=[codigo_empleado_fk])
    contrato_tipo_rel   = relationship("ContratoTipo",  foreign_keys=[codigo_contrato_tipo_fk])
    cargo_rel           = relationship("Cargo",         foreign_keys=[codigo_cargo_fk])
    grupo_rel           = relationship("Grupo",         foreign_keys=[codigo_grupo_fk])
    tercero_rel         = relationship("Tercero",       foreign_keys=[codigo_tercero_fk])
    puesto_rel          = relationship("Puesto",        foreign_keys=[codigo_puesto_fk])
    entidad_salud_rel   = relationship("Entidad",       foreign_keys=[codigo_entidad_salud_fk])
    entidad_pension_rel = relationship("Entidad",       foreign_keys=[codigo_entidad_pension_fk])
    entidad_cesantia_rel= relationship("Entidad",       foreign_keys=[codigo_entidad_cesantia_fk])
    entidad_caja_rel    = relationship("Entidad",       foreign_keys=[codigo_entidad_caja_fk])
    ciudad_contrato_rel = relationship(Ciudad,          foreign_keys=[codigo_ciudad_contrato_fk])
    ciudad_labora_rel   = relationship(Ciudad,          foreign_keys=[codigo_ciudad_labora_fk])
