from sqlalchemy import Boolean, Column, Float, Integer, String, Date, ForeignKey
from sqlalchemy.orm import relationship
from app.core.tenant_database import Base


class Embargo(Base):
    __tablename__ = "rhu_embargo"

    codigo_embargo_pk = Column(Integer, primary_key=True, index=True)
    codigo_embargo_tipo_fk = Column(String(10), nullable=True)
    codigo_embargo_juzgado_fk = Column(String(30), nullable=True)
    codigo_empleado_fk = Column(Integer, ForeignKey("rhu_empleado.codigo_empleado_pk"), nullable=True, index=True)
    codigo_empresa_fk = Column(Integer)
    fecha = Column(Date)
    numero = Column(String(30), nullable=True)
    estado_activo = Column(Boolean, default=False)
    estado_autorizado = Column(Boolean, default=False)
    estado_aprobado = Column(Boolean, default=False)
    estado_anulado = Column(Boolean, default=False)
    valor_fijo = Column(Boolean, default=False, nullable=True)
    oficina_destino = Column(String(4), nullable=True)
    consecutivo_juzgado = Column(String(5), nullable=True)
    codigo_instancia = Column(String(2), nullable=True)
    porcentaje_devengado = Column(Boolean, default=False, nullable=True)
    porcentaje_devengado_prestacional = Column(Boolean, default=False, nullable=True)
    porcentaje_devengado_prestacional_menos_descuento_ley = Column(Boolean, default=False, nullable=True)
    por_devengado_prestacional_menos_descuento_ley_transporte = Column(Boolean, default=False, nullable=True)
    porcentaje_devengado_prestacional_menos_transporte = Column(Boolean, default=False, nullable=True)
    porcentaje_devengado_menos_descuento_ley = Column(Boolean, default=False, nullable=True)
    porcentaje_devengado_menos_descuento_ley_transporte = Column(Boolean, default=False, nullable=True)
    porcentaje_exceda_salario_minimo = Column(Boolean, default=False, nullable=True)
    porcentaje_exceda_salario_minimo_prestacional_menos_transporte = Column(Boolean, default=False, nullable=True)
    porcentaje_exceda_salario_minimo_prestacional_menos_ley_tte = Column(Boolean, default=False, nullable=True)
    porcentaje_salario_minimo = Column(Boolean, default=False, nullable=True)
    partes_exceda_salario_minimo = Column(Boolean, default=False, nullable=True)
    partes_exceda_salario_minimo_menos_descuento_ley = Column(Boolean, default=False, nullable=True)
    par_exceda_sal_minimo_prestacional_menos_des_ley = Column(Boolean, default=False, nullable=True)
    partes = Column(Float, default=0.0)
    vr_valor = Column(Float, default=0.0, nullable=True)
    porcentaje = Column(Float, default=0.0, nullable=True)
    vr_abonos = Column(Float, default=0.0)
    codigo_usuario = Column(String(50), nullable=True)
    comentarios = Column(String(200), nullable=True)
    cuenta = Column(String(50), nullable=True)
    tipo_cuenta = Column(String(50), nullable=True)
    numero_expediente = Column(String(50), nullable=True)
    numero_proceso = Column(String(50), nullable=True)
    numero_radicado = Column(String(50), nullable=True)
    oficio = Column(String(50), nullable=True)
    oficio_inactivacion = Column(String(50), nullable=True)
    fecha_inicio_folio = Column(Date, nullable=True)
    fecha_inactivacion = Column(Date, nullable=True)
    numero_identificacion_demandante = Column(String(20), nullable=True)
    nombre_corto_demandante = Column(String(80), nullable=True)
    apellidos_demandante = Column(String(80), nullable=True)
    numero_identificacion_beneficiario = Column(String(20), nullable=True)
    nombre_corto_beneficiario = Column(String(80), nullable=True)
    oficina = Column(String(30), nullable=True)
    vr_monto_maximo = Column(Float, default=0.0, nullable=True)
    saldo = Column(Float, default=0.0, nullable=True)
    descuento = Column(Float, default=0.0, nullable=True)
    validar_monto_maximo = Column(Boolean, default=False, nullable=True)
    afecta_nomina = Column(Boolean, default=False, nullable=True)
    afecta_vacacion = Column(Boolean, default=False, nullable=True)
    afecta_prima = Column(Boolean, default=False, nullable=True)
    afecta_liquidacion = Column(Boolean, default=False, nullable=True)
    afecta_cesantia = Column(Boolean, default=False, nullable=True)
    afecta_indemnizacion = Column(Boolean, default=False, nullable=True)
    descontar_novedad = Column(Boolean, default=False)

    empleado_rel = relationship("Empleado", foreign_keys=[codigo_empleado_fk])

    @property
    def empleado_nombre(self) -> str | None:
        return self.empleado_rel.nombre_corto if self.empleado_rel else None
