from sqlalchemy import Boolean, Column, Date, Float, ForeignKey, Integer, String
from sqlalchemy.orm import relationship
from app.core.tenant_database import Base


class Empleado(Base):
    __tablename__ = "rhu_empleado"

    codigo_empleado_pk = Column(Integer, primary_key=True, index=True, autoincrement=True)
    codigo_identificacion_fk = Column(String(3), ForeignKey("gen_identificacion.codigo_identificacion_pk"), nullable=True)
    codigo_contrato_fk = Column(Integer, ForeignKey("rhu_contrato.codigo_contrato_pk"), nullable=True)
    codigo_cuenta_tipo_fk = Column(String(10), nullable=True)
    codigo_raza_fk = Column(String(10), nullable=True)
    codigo_contrato_ultimo_fk = Column(Integer, nullable=True)
    codigo_contrato_registro_fk = Column(Integer, nullable=True)
    numero_identificacion = Column(String(20), nullable=False)
    digito_verificacion = Column(String(1), nullable=True)
    discapacidad = Column(Boolean, default=False, nullable=False)
    desplazado = Column(Boolean, default=False, nullable=False)
    victima_conflicto_armado = Column(Boolean, default=False, nullable=False)
    reincorporados = Column(Boolean, default=False, nullable=False)
    afrodescendientes = Column(Boolean, default=False, nullable=False)
    madre_cabeza_familia = Column(Boolean, default=False, nullable=False)
    carro = Column(Boolean, default=False, nullable=False)
    moto = Column(Boolean, default=False, nullable=False)
    transporte_publico = Column(Boolean, default=False, nullable=False)
    bicicleta = Column(Boolean, default=False, nullable=False)
    padre_familia = Column(Boolean, default=False, nullable=False)
    cabeza_hogar = Column(Boolean, default=False, nullable=False)
    barrio = Column(String(100), nullable=True)
    talla_camisa = Column(String(10), nullable=True)
    talla_pantalon = Column(String(10), nullable=True)
    talla_calzado = Column(String(10), nullable=True)
    talla_kepis = Column(String(10), nullable=True)
    estatura = Column(Integer, nullable=True, default=0)
    peso = Column(Integer, nullable=True, default=0)
    estado_contrato = Column(Boolean, default=False, nullable=False)
    nombre_corto = Column(String(80), nullable=True)
    nombre1 = Column(String(30), nullable=True)
    nombre2 = Column(String(30), nullable=True)
    apellido1 = Column(String(30), nullable=True)
    apellido2 = Column(String(30), nullable=True)
    telefono = Column(String(15), nullable=True)
    celular = Column(String(20), nullable=True)
    direccion = Column(String(120), nullable=True)
    libreta_militar = Column(String(50), nullable=True)
    distrito_militar = Column(String(100), nullable=True)
    codigo_libreta_clase_fk = Column(String(10), nullable=True)
    numero_hijos = Column(Integer, nullable=True, default=0)
    codigo_ciudad_fk = Column(Integer, nullable=True)
    codigo_ciudad_expedicion_identificacion_fk = Column(Integer, nullable=True)
    fecha_expedicion_identificacion = Column(Date, nullable=True)
    fecha_induccion = Column(Date, nullable=True)
    fecha_ultima_reinduccion = Column(Date, nullable=True)
    codigo_rh_fk = Column(String(10), nullable=True)
    codigo_sexo_fk = Column(String(1), nullable=True)
    correo = Column(String(80), nullable=True)
    correo_corporativo = Column(String(80), nullable=True)
    fecha_nacimiento = Column(Date, nullable=True)
    codigo_ciudad_nacimiento_fk = Column(Integer, nullable=True)
    codigo_estado_civil_fk = Column(String(10), nullable=True)
    cuenta = Column(String(80), nullable=True)
    codigo_banco_fk = Column(String(10), ForeignKey("gen_banco.codigo_banco_pk"), nullable=True)
    permiso_especial = Column(String(15), nullable=True)
    codigo_nivel_estudio_fk = Column(String(20), nullable=True)
    codigo_zona_fk = Column(String(10), ForeignKey("rhu_zona.codigo_zona_pk"), nullable=True)
    codigo_subzona_fk = Column(String(10), nullable=True)
    codigo_sector_fk = Column(String(10), nullable=True)
    codigo_departamento_fk = Column(String(10), nullable=True)
    puesto = Column(String(200), nullable=True)
    codigo_segmento_fk = Column(String(10), nullable=True)
    fecha_bloqueo_programacion = Column(Date, nullable=True)
    fecha_acreditacion = Column(Date, nullable=True)
    fecha_poligono = Column(Date, nullable=True)
    fecha_psicofisico = Column(Date, nullable=True)
    fecha_psicosensometrico = Column(Date, nullable=True)
    estrato = Column(String(10), nullable=True)
    vivienda_tipo = Column(String(20), nullable=True)
    codigo_tercero_fk = Column(Integer, nullable=True)
    codigo_religion_fk = Column(String(10), nullable=True)
    codigo_grupo_voluntariado_fk = Column(String(10), nullable=True)
    codigo_grupo_etnico_fk = Column(String(10), nullable=True)
    codigo_permiso_especial_tipo_fk = Column(String(10), nullable=True)
    lgbt = Column(Boolean, default=False, nullable=False)
    adulto_mayor = Column(Boolean, default=False, nullable=False)
    victima_violencia = Column(Boolean, default=False, nullable=False)
    desplazado_violencia = Column(Boolean, default=False, nullable=False)
    desplazado_fenomeno_natural = Column(Boolean, default=False, nullable=False)
    usuario = Column(String(50), nullable=True)
    religion_otro = Column(String(50), nullable=True)
    raza_otro = Column(String(50), nullable=True)
    grupo_voluntariado_otro = Column(String(50), nullable=True)
    grupo_etnico_otro = Column(String(50), nullable=True)
    discapacidadtipo_otro = Column(String(50), nullable=True)
    codigo_discapacidad_tipo_fk = Column(String(10), nullable=True)
    omitir_adicional_puesto = Column(Boolean, default=False, nullable=False)
    codigo_estructura_fk = Column(String(20), nullable=True)
    derecho_dependientes = Column(Boolean, default=False)
    vr_pagos_por_salud_prepagada = Column(Float, default=0.0)
    vr_interes_vivienda = Column(Float, default=0.0)
    vr_retencion_fuente_propuesto = Column(Float, default=0.0)
    vr_retencion_fuente_base = Column(Float, default=0.0)
    vr_aporte_afc_propuesto = Column(Float, default=0.0)
    fecha_examen_ingreso = Column(Date, nullable=True)
    codigo_empresa_fk = Column(Integer, nullable=True)
    fecha_actualizacion = Column(Date, nullable=True)
    codigo_interno = Column(String(30), nullable=True)
    vetado = Column(Boolean, default=False, nullable=False)
    correo_verificado = Column(Boolean, default=False, nullable=False)
    codigo_verificacion_correo = Column(String(6), nullable=True)

    banco_rel = relationship("Banco", foreign_keys=[codigo_banco_fk])
    zona_rel = relationship("Zona", foreign_keys=[codigo_zona_fk])
    identificacion_rel = relationship("Identificacion", foreign_keys=[codigo_identificacion_fk])
    contrato_rel = relationship("Contrato", foreign_keys=[codigo_contrato_fk])

    @property
    def cargo_nombre(self) -> str | None:
        if self.contrato_rel and self.contrato_rel.cargo_rel:
            return self.contrato_rel.cargo_rel.nombre
        return None

    @property
    def grupo_nombre(self) -> str | None:
        if self.contrato_rel and self.contrato_rel.grupo_rel:
            return self.contrato_rel.grupo_rel.nombre
        return None
