"""initial_master

Revision ID: 05db3f63428e
Revises: 
Create Date: 2026-03-12 15:05:38.499339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05db3f63428e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nombres', sa.String(length=150), nullable=True))
    op.add_column('user', sa.Column('apellidos', sa.String(length=150), nullable=True))
    op.add_column('user', sa.Column('numero_identificacion', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'numero_identificacion')
    op.drop_column('user', 'apellidos')
    op.drop_column('user', 'nombres')
    # ### end Alembic commands ###
