"""Ajustes modelo gen_item y creación modelo impuesto e impueto_tipo

Revision ID: 1cea0c87b28b
Revises: 766f94298f51
Create Date: 2026-03-25 15:59:03.292979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cea0c87b28b'
down_revision: Union[str, Sequence[str], None] = '766f94298f51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
