"""Crear tablas gen_movimiento, gen_movimiento_detalle y gen_movimiento_tipo

Revision ID: 2a429c1d3759
Revises: 1cea0c87b28b
Create Date: 2026-03-27 16:51:06.176467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a429c1d3759'
down_revision: Union[str, Sequence[str], None] = '1cea0c87b28b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
