"""descripcion del cambio

Revision ID: 40b20315cd9f
Revises: 3eaca3b8ed14
Create Date: 2026-03-12 16:59:10.657283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40b20315cd9f'
down_revision: Union[str, Sequence[str], None] = '3eaca3b8ed14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('verification_token', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_verification_token'), 'user', ['verification_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_verification_token'), table_name='user')
    op.drop_column('user', 'verification_token')
    op.drop_column('user', 'is_verified')
    # ### end Alembic commands ###
