"""add_fields_mas_credito_solicitud

Revision ID: 6e03b9734f35
Revises: a4e9bc9f8a6c
Create Date: 2026-04-06 08:46:19.419174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e03b9734f35'
down_revision: Union[str, Sequence[str], None] = 'a4e9bc9f8a6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mas_credito_solicitud',
    sa.Column('codigo_credito_solicitud_pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('plazo', sa.Integer(), nullable=False),
    sa.Column('tasa_interes', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('codigo_credito_solicitud_pk')
    )
    op.create_index(op.f('ix_mas_credito_solicitud_codigo_credito_solicitud_pk'), 'mas_credito_solicitud', ['codigo_credito_solicitud_pk'], unique=False)
    op.create_index(op.f('ix_mas_credito_solicitud_usuario_id'), 'mas_credito_solicitud', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mas_credito_solicitud_usuario_id'), table_name='mas_credito_solicitud')
    op.drop_index(op.f('ix_mas_credito_solicitud_codigo_credito_solicitud_pk'), table_name='mas_credito_solicitud')
    op.drop_table('mas_credito_solicitud')
    # ### end Alembic commands ###
