"""add_reset_password_token_to_user

Revision ID: 766f94298f51
Revises: fd475da347a0
Create Date: 2026-03-19 09:34:22.341513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '766f94298f51'
down_revision: Union[str, Sequence[str], None] = 'fd475da347a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('reset_password_token', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_reset_password_token'), 'user', ['reset_password_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_reset_password_token'), table_name='user')
    op.drop_column('user', 'reset_password_token')
    # ### end Alembic commands ###
