"""atributos para tenant de credito y anticipo

Revision ID: 96074945ba27
Revises: d8f01fe9e7d4
Create Date: 2026-03-28 07:17:37.792756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96074945ba27'
down_revision: Union[str, Sequence[str], None] = 'd8f01fe9e7d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('credito', sa.Boolean(), nullable=True))
    op.add_column('tenant', sa.Column('anticipo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant', 'anticipo')
    op.drop_column('tenant', 'credito')
    # ### end Alembic commands ###
