"""varios

Revision ID: a4e9bc9f8a6c
Revises: 383fcf4d516c
Create Date: 2026-03-28 11:33:20.807787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4e9bc9f8a6c'
down_revision: Union[str, Sequence[str], None] = '383fcf4d516c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('activo', sa.Boolean(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant', 'activo')
    # ### end Alembic commands ###
