"""notificacion

Revision ID: bf69b0b1ba8b
Revises: 911da898445e
Create Date: 2026-03-28 08:44:01.797734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bf69b0b1ba8b'
down_revision: Union[str, Sequence[str], None] = '911da898445e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_notificacion_id'), table_name='auth_notificacion')
    op.drop_index(op.f('ix_auth_notificacion_usuario_id'), table_name='auth_notificacion')
    op.drop_table('auth_notificacion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_notificacion',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('titulo', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('mensaje', mysql.TEXT(), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('leida', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('fecha_creacion', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], name=op.f('auth_notificacion_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_auth_notificacion_usuario_id'), 'auth_notificacion', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_auth_notificacion_id'), 'auth_notificacion', ['id'], unique=False)
    # ### end Alembic commands ###
