"""add fecha_creacion to user

Revision ID: c2a5e8bf8571
Revises: 2be0709940c3
Create Date: 2026-06-16 09:37:27.221408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2a5e8bf8571'
down_revision: Union[str, Sequence[str], None] = '2be0709940c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Se agrega con server_default = CURRENT_TIMESTAMP para que los registros
    # existentes queden con la fecha/hora actual (la columna es NOT NULL).
    op.add_column(
        'user',
        sa.Column(
            'fecha_creacion',
            sa.DateTime(),
            nullable=False,
            server_default=sa.text('CURRENT_TIMESTAMP'),
        ),
    )
    # Se retira el server_default: a partir de ahora el valor lo asigna la app
    # (default del modelo) en cada nuevo registro.
    op.alter_column('user', 'fecha_creacion', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'fecha_creacion')
    # ### end Alembic commands ###
