"""Crear tablas gen_movimiento, gen_movimiento_detalle y gen_movimiento_tipo

Revision ID: d8f01fe9e7d4
Revises: 2a429c1d3759
Create Date: 2026-03-27 17:01:48.601753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8f01fe9e7d4'
down_revision: Union[str, Sequence[str], None] = '2a429c1d3759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
