"""Atributos de empleado

Revision ID: fd475da347a0
Revises: 6ec2b6b29af0
Create Date: 2026-03-17 07:58:45.638248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd475da347a0'
down_revision: Union[str, Sequence[str], None] = '6ec2b6b29af0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('empleado_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'empleado_id')
    # ### end Alembic commands ###
