from sqlalchemy import Boolean, Column, Float, Integer, String, Time
from app.core.tenant_database import Base


class PedidoDetalle(Base):
    __tablename__ = "tur_pedido_detalle"

    codigo_pedido_detalle_pk = Column(Integer, primary_key=True, index=True)
    codigo_pedido_fk = Column(Integer, index=True)
    codigo_concepto_fk = Column(Integer, nullable=True)
    codigo_item_fk = Column(Integer)
    codigo_modalidad_fk = Column(String(10), nullable=True)
    codigo_puesto_fk = Column(Integer)
    codigo_contrato_detalle_fk = Column(Integer, nullable=True)
    codigo_cotizacion_detalle_fk = Column(Integer, nullable=True)
    periodo = Column(String(1), nullable=True)
    anio = Column(Integer, default=0)
    mes = Column(Integer, default=0)
    dia_desde = Column(Integer, default=1)
    dia_hasta = Column(Integer, default=1)
    dias = Column(Integer, default=0)
    horas_unidad = Column(Float, default=0.0)
    horas_diurnas_unidad = Column(Float, default=0.0)
    horas_nocturnas_unidad = Column(Float, default=0.0)
    horas = Column(Float, default=0.0)
    horas_diurnas = Column(Float, default=0.0)
    horas_nocturnas = Column(Float, default=0.0)
    horas_programadas = Column(Float, default=0.0)
    horas_diurnas_programadas = Column(Float, default=0.0)
    horas_nocturnas_programadas = Column(Float, default=0.0)
    cantidad = Column(Integer, default=0)
    vr_precio_ajustado = Column(Float, nullable=True, default=0.0)
    vr_precio_minimo = Column(Float, default=0.0)
    vr_precio = Column(Float, default=0.0)
    vr_precio_adicional = Column(Float, default=0.0)
    porcentaje_iva = Column(Float, nullable=True, default=0.0)
    porcentaje_base_iva = Column(Float, nullable=True, default=0.0)
    vr_subtotal = Column(Float, default=0.0)
    vr_devolucion = Column(Float, default=0.0)
    vr_adicion = Column(Float, default=0.0)
    vr_iva = Column(Float, default=0.0)
    vr_base_iva = Column(Float, default=0.0)
    vr_total = Column(Float, default=0.0)
    vr_afectado = Column(Float, default=0.0)
    vr_saldo = Column(Float, default=0.0)
    lunes = Column(Boolean, default=False)
    martes = Column(Boolean, default=False)
    miercoles = Column(Boolean, default=False)
    jueves = Column(Boolean, default=False)
    viernes = Column(Boolean, default=False)
    sabado = Column(Boolean, default=False)
    domingo = Column(Boolean, default=False)
    festivo = Column(Boolean, default=False)
    detalle = Column(String(500), nullable=True)
    detalle_factura = Column(String(150), nullable=True)
    vr_salario_base = Column(Float, default=0.0)
    hora_desde = Column(Time, nullable=True)
    hora_hasta = Column(Time, nullable=True)
    compuesto = Column(Boolean, default=False)
    estado_terminado = Column(Boolean, default=False)
    estado_programado = Column(Boolean, default=False)
    estado_descartado_programacion = Column(Boolean, default=False)
    dias_reales = Column(Boolean, default=False)
    codigo_grupo_fk = Column(Integer, nullable=True)
    programar = Column(Boolean, default=False)
    cortesia = Column(Boolean, default=False)
    codigo_pedido_detalle_fk = Column(Integer, nullable=True)
    horario = Column(String(500), nullable=True)
    codigo_grupo_facturacion_fk = Column(Integer, nullable=True)
    moto = Column(Boolean, default=False)
    carro = Column(Boolean, default=False)
    cuatrimoto = Column(Boolean, default=False)
    codigo_empresa_fk = Column(Integer)
