from sqlalchemy import Boolean, Column, ForeignKey, Integer, String, Float
from sqlalchemy.orm import relationship
from app.core.tenant_database import Base


class Programacion(Base):
    __tablename__ = "tur_programacion"

    codigo_programacion_pk = Column(Integer, primary_key=True, index=True)
    codigo_pedido_fk = Column(Integer, ForeignKey("tur_pedido.codigo_pedido_pk"), nullable=True)
    codigo_pedido_detalle_fk = Column(Integer, ForeignKey("tur_pedido_detalle.codigo_pedido_detalle_pk"), nullable=True)
    codigo_puesto_fk = Column(Integer, ForeignKey("tur_puesto.codigo_puesto_pk"), nullable=True)
    codigo_empleado_fk = Column(Integer, ForeignKey("rhu_empleado.codigo_empleado_pk"), index=True)
    codigo_contrato_fk = Column(Integer, ForeignKey("rhu_contrato.codigo_contrato_pk"), nullable=True)
    codigo_empresa_fk = Column(Integer, nullable=True)
    anio = Column(Integer, default=0)
    mes = Column(Integer, default=0)
    dia_1 = Column(String(5), nullable=True)
    dia_2 = Column(String(5), nullable=True)
    dia_3 = Column(String(5), nullable=True)
    dia_4 = Column(String(5), nullable=True)
    dia_5 = Column(String(5), nullable=True)
    dia_6 = Column(String(5), nullable=True)
    dia_7 = Column(String(5), nullable=True)
    dia_8 = Column(String(5), nullable=True)
    dia_9 = Column(String(5), nullable=True)
    dia_10 = Column(String(5), nullable=True)
    dia_11 = Column(String(5), nullable=True)
    dia_12 = Column(String(5), nullable=True)
    dia_13 = Column(String(5), nullable=True)
    dia_14 = Column(String(5), nullable=True)
    dia_15 = Column(String(5), nullable=True)
    dia_16 = Column(String(5), nullable=True)
    dia_17 = Column(String(5), nullable=True)
    dia_18 = Column(String(5), nullable=True)
    dia_19 = Column(String(5), nullable=True)
    dia_20 = Column(String(5), nullable=True)
    dia_21 = Column(String(5), nullable=True)
    dia_22 = Column(String(5), nullable=True)
    dia_23 = Column(String(5), nullable=True)
    dia_24 = Column(String(5), nullable=True)
    dia_25 = Column(String(5), nullable=True)
    dia_26 = Column(String(5), nullable=True)
    dia_27 = Column(String(5), nullable=True)
    dia_28 = Column(String(5), nullable=True)
    dia_29 = Column(String(5), nullable=True)
    dia_30 = Column(String(5), nullable=True)
    dia_31 = Column(String(5), nullable=True)
    horas = Column(Float, default=0.0)
    horas_diurnas = Column(Float, default=0.0)
    horas_nocturnas = Column(Float, default=0.0)
    complementario = Column(Boolean, default=False, nullable=True)
    adicional = Column(Boolean, default=False, nullable=True)
    periodo_bloqueo = Column(Integer, default=0)
    reporte = Column(Boolean, default=False, nullable=True)
    recursivo = Column(Boolean, default=False)

    pedido_rel = relationship("Pedido", foreign_keys=[codigo_pedido_fk])
    pedido_detalle_rel = relationship("PedidoDetalle", foreign_keys=[codigo_pedido_detalle_fk])
    puesto_rel = relationship("Puesto", foreign_keys=[codigo_puesto_fk])
    empleado_rel = relationship("Empleado", foreign_keys=[codigo_empleado_fk])
    contrato_rel = relationship("Contrato", foreign_keys=[codigo_contrato_fk])
